# Generated by Django 5.2.1 on 2026-08-17 02:03

import django.db.models.deletion
import uuid
import verification.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("company", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Verification",
            fields=[
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("PROCESSING", "PROCESSING"),
                            ("COMPLETED", "COMPLETED"),
                            ("FAILED", "FAILED"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("progress", models.PositiveIntegerField(default=0)),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "certificate",
                    models.FileField(
                        upload_to="certificates/",
                        validators=[verification.validators.validate_file_size],
                    ),
                ),
                ("platform", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "student_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "course_name",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("issuer", models.CharField(blank=True, max_length=255, null=True)),
                ("verification_url", models.TextField(blank=True, null=True)),
                ("url_valid", models.BooleanField(default=False)),
                ("authenticity_score", models.IntegerField(default=0)),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("GENUINE", "GENUINE"),
                            ("SUSPICIOUS", "SUSPICIOUS"),
                            ("FAKE", "FAKE"),
                        ],
                        max_length=20,
                    ),
                ),
                ("raw_result", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verifications",
                        to="company.company",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
